generatorName: typescript-axios
outputDir: mitxonline-api-clients/src/typescript/mitxonline-api-axios/src/v2
inputSpec: mitxonline/openapi/specs/v2.yaml
ignoreFileOverride: mitxonline-api-clients/.openapi-generator-ignore
additionalProperties:
  paramNaming: original
  useSingleRequestParameter: true
  supportsES6: false
