/* tslint:disable */
/* eslint-disable */
/**
 * MITx Online API
 * MIT public API
 *
 * The version of the OpenAPI document: 0.0.1 (v3)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * Minimal CourseRun model serializer
 */
export interface BaseCourseRun {
    /**
     * The title of the course. This value is synced automatically with edX studio.
     */
    'title': string;
    /**
     * The day the course begins. This value is synced automatically with edX studio.
     */
    'start_date'?: string | null;
    /**
     * The last day the course is active. This value is synced automatically with edX studio.
     */
    'end_date'?: string | null;
    /**
     * The first day students can enroll. This value is synced automatically with edX studio.
     */
    'enrollment_start'?: string | null;
    /**
     * The last day students can enroll. This value is synced automatically with edX studio.
     */
    'enrollment_end'?: string | null;
    /**
     * The date beyond which the learner should not see link to this course run on their dashboard.
     */
    'expiration_date'?: string | null;
    /**
     * Get the courseware URL
     */
    'courseware_url': string | null;
    'courseware_id': string;
    /**
     * The day certificates should be available to users. This value is synced automatically with edX studio.
     */
    'certificate_available_date'?: string | null;
    /**
     * The date beyond which the learner can not enroll in paid course mode.
     */
    'upgrade_deadline'?: string | null;
    /**
     * Check if the course run is upgradable
     */
    'is_upgradable': boolean;
    /**
     * Check if the course run is enrollable
     */
    'is_enrollable': boolean;
    /**
     * Check if the course run is archived
     */
    'is_archived': boolean;
    'is_self_paced'?: boolean;
    /**
     * A string that identifies the set of runs that this run belongs to (example: \'R2\')
     */
    'run_tag': string;
    'id': number;
    'live'?: boolean;
    /**
     * Get the course number
     */
    'course_number': string;
    /**
     * Get the enrollment modes for the course run
     */
    'enrollment_modes': Array<{ [key: string]: any; }>;
    /**
     * ISO 639-1 language code for this run (e.g. \'en\', \'zh\', \'fr\'). Leave blank for unspecified.  * `af_ZA` - af_ZA * `ar` - ar * `az` - az * `bo` - bo * `da` - da * `de` - de * `de_DE` - de_DE * `el` - el * `es_419` - es_419 * `es_ES` - es_ES * `en` - en * `fa` - fa * `fr` - fr * `fr_CA` - fr_CA * `he` - he * `hi` - hi * `hu` - hu * `id` - id * `it_IT` - it_IT * `ja` - ja * `ka` - ka * `kk` - kk * `ko` - ko * `lv` - lv * `nl` - nl * `pl` - pl * `pt_BR` - pt_BR * `pt_PT` - pt_PT * `ro` - ro * `ru` - ru * `sq` - sq * `sv` - sv * `sw` - sw * `te` - te * `th` - th * `tr_TR` - tr_TR * `uk` - uk * `uz` - uz * `vi` - vi * `zh_CN` - zh_CN * `zh_HANS` - zh_HANS * `zh_HK` - zh_HK
     */
    'language'?: BaseCourseRunLanguageEnum;
    /**
     * Designates this run as the primary-language version for its run-tag group. The primary run is used as the canonical run when grouping language variants. If no run in a group is marked primary, the oldest run by creation date is treated as primary.
     */
    'is_primary_language'?: boolean;
    /**
     * Return the label for the language, using the override if necessary
     */
    'language_label': string;
    /**
     * Variant: Describes the industry the run is adapted for.  * `` - Original * `E` - Energy * `F` - Finance * `HC` - Healthcare * `M` - Manufacturing
     */
    'variant_industry'?: BaseCourseRunVariantIndustryEnum;
    /**
     * Return the display label for the variant industry.
     */
    'variant_industry_label': string;
    /**
     * Variant: Describes the length of the run (short/long).  * `` - Full * `S` - Short
     */
    'variant_length'?: BaseCourseRunVariantLengthEnum;
    /**
     * Return the display label for the variant length.
     */
    'variant_length_label': string;
    'course_id': number;
}

export const BaseCourseRunLanguageEnum = {
    AfZa: 'af_ZA',
    Ar: 'ar',
    Az: 'az',
    Bo: 'bo',
    Da: 'da',
    De: 'de',
    DeDe: 'de_DE',
    El: 'el',
    Es419: 'es_419',
    EsEs: 'es_ES',
    En: 'en',
    Fa: 'fa',
    Fr: 'fr',
    FrCa: 'fr_CA',
    He: 'he',
    Hi: 'hi',
    Hu: 'hu',
    Id: 'id',
    ItIt: 'it_IT',
    Ja: 'ja',
    Ka: 'ka',
    Kk: 'kk',
    Ko: 'ko',
    Lv: 'lv',
    Nl: 'nl',
    Pl: 'pl',
    PtBr: 'pt_BR',
    PtPt: 'pt_PT',
    Ro: 'ro',
    Ru: 'ru',
    Sq: 'sq',
    Sv: 'sv',
    Sw: 'sw',
    Te: 'te',
    Th: 'th',
    TrTr: 'tr_TR',
    Uk: 'uk',
    Uz: 'uz',
    Vi: 'vi',
    ZhCn: 'zh_CN',
    ZhHans: 'zh_HANS',
    ZhHk: 'zh_HK',
    Empty: '',
} as const;

export type BaseCourseRunLanguageEnum = typeof BaseCourseRunLanguageEnum[keyof typeof BaseCourseRunLanguageEnum];
export const BaseCourseRunVariantIndustryEnum = {
    E: 'E',
    F: 'F',
    Hc: 'HC',
    M: 'M',
    Empty: '',
} as const;

export type BaseCourseRunVariantIndustryEnum = typeof BaseCourseRunVariantIndustryEnum[keyof typeof BaseCourseRunVariantIndustryEnum];
export const BaseCourseRunVariantLengthEnum = {
    /**
    * * &#x60;&#x60; - Full
* &#x60;S&#x60; - Short
    */
    S: 'S',
    /**
    * 
    */
    Empty: '',
} as const;

export type BaseCourseRunVariantLengthEnum = typeof BaseCourseRunVariantLengthEnum[keyof typeof BaseCourseRunVariantLengthEnum];


export const BlankEnum = {
    Empty: '',
} as const;

export type BlankEnum = typeof BlankEnum[keyof typeof BlankEnum];


export interface CourseOutlineBadRequestResponse {
    'detail': string;
}
/**
 * A single module within a course outline.
 */
export interface CourseOutlineModule {
    'id': string;
    'title': string;
    'effort_time': number;
    'effort_activities': number;
    'counts': CourseOutlineModuleCounts;
}
/**
 * Activity counts within a course outline module.
 */
export interface CourseOutlineModuleCounts {
    'videos': number;
    'readings': number;
    'problems': number;
    'assignments': number;
    'app_items': number;
}
/**
 * Course outline data fetched from Open edX.
 */
export interface CourseOutlineResponse {
    'course_id': string;
    'generated_at': string;
    'modules': Array<CourseOutlineModule>;
}
export interface CourseOutlineServerErrorResponse {
    'detail': string;
}
export interface CourseOutlineUpstreamErrorResponse {
    'detail': string;
}
/**
 * CourseRunEnrollment model serializer
 */
export interface CourseRunEnrollmentV3 {
    'id': number;
    'edx_emails_subscription'?: boolean;
    'certificate': V3CourseRunCertificate | null;
    'enrollment_mode': EnrollmentModeEnum;
    'grades': Array<CourseRunGrade>;
    'run': CourseRunWithCourseV3;
    'b2b_organization_id': number | null;
    'b2b_contract_id': number | null;
}


/**
 * CourseRunEnrollment model serializer
 */
export interface CourseRunEnrollmentV3Request {
    'edx_emails_subscription'?: boolean;
}
/**
 * CourseRunGrade serializer
 */
export interface CourseRunGrade {
    'grade': number;
    'letter_grade': string | null;
    'passed': boolean;
    'set_by_admin': boolean;
    /**
     * Returns the grade field value as a number out of 100 (or Decimal(0) if the value is None)
     */
    'grade_percent': number;
}
/**
 * CourseRun serializer
 */
export interface CourseRunWithCourseV3 {
    /**
     * The title of the course. This value is synced automatically with edX studio.
     */
    'title': string;
    /**
     * The day the course begins. This value is synced automatically with edX studio.
     */
    'start_date'?: string | null;
    /**
     * The last day the course is active. This value is synced automatically with edX studio.
     */
    'end_date'?: string | null;
    /**
     * The first day students can enroll. This value is synced automatically with edX studio.
     */
    'enrollment_start'?: string | null;
    /**
     * The last day students can enroll. This value is synced automatically with edX studio.
     */
    'enrollment_end'?: string | null;
    /**
     * The date beyond which the learner should not see link to this course run on their dashboard.
     */
    'expiration_date'?: string | null;
    /**
     * Get the courseware URL
     */
    'courseware_url': string | null;
    'courseware_id': string;
    /**
     * The day certificates should be available to users. This value is synced automatically with edX studio.
     */
    'certificate_available_date'?: string | null;
    /**
     * The date beyond which the learner can not enroll in paid course mode.
     */
    'upgrade_deadline'?: string | null;
    /**
     * Check if the course run is upgradable
     */
    'is_upgradable': boolean;
    /**
     * Check if the course run is enrollable
     */
    'is_enrollable': boolean;
    /**
     * Check if the course run is archived
     */
    'is_archived': boolean;
    'is_self_paced'?: boolean;
    /**
     * A string that identifies the set of runs that this run belongs to (example: \'R2\')
     */
    'run_tag': string;
    'id': number;
    'live'?: boolean;
    /**
     * Get the course number
     */
    'course_number': string;
    /**
     * Get the enrollment modes for the course run
     */
    'enrollment_modes': Array<{ [key: string]: any; }>;
    /**
     * ISO 639-1 language code for this run (e.g. \'en\', \'zh\', \'fr\'). Leave blank for unspecified.  * `af_ZA` - af_ZA * `ar` - ar * `az` - az * `bo` - bo * `da` - da * `de` - de * `de_DE` - de_DE * `el` - el * `es_419` - es_419 * `es_ES` - es_ES * `en` - en * `fa` - fa * `fr` - fr * `fr_CA` - fr_CA * `he` - he * `hi` - hi * `hu` - hu * `id` - id * `it_IT` - it_IT * `ja` - ja * `ka` - ka * `kk` - kk * `ko` - ko * `lv` - lv * `nl` - nl * `pl` - pl * `pt_BR` - pt_BR * `pt_PT` - pt_PT * `ro` - ro * `ru` - ru * `sq` - sq * `sv` - sv * `sw` - sw * `te` - te * `th` - th * `tr_TR` - tr_TR * `uk` - uk * `uz` - uz * `vi` - vi * `zh_CN` - zh_CN * `zh_HANS` - zh_HANS * `zh_HK` - zh_HK
     */
    'language'?: CourseRunWithCourseV3LanguageEnum;
    /**
     * Designates this run as the primary-language version for its run-tag group. The primary run is used as the canonical run when grouping language variants. If no run in a group is marked primary, the oldest run by creation date is treated as primary.
     */
    'is_primary_language'?: boolean;
    /**
     * Return the label for the language, using the override if necessary
     */
    'language_label': string;
    /**
     * Variant: Describes the industry the run is adapted for.  * `` - Original * `E` - Energy * `F` - Finance * `HC` - Healthcare * `M` - Manufacturing
     */
    'variant_industry'?: CourseRunWithCourseV3VariantIndustryEnum;
    /**
     * Return the display label for the variant industry.
     */
    'variant_industry_label': string;
    /**
     * Variant: Describes the length of the run (short/long).  * `` - Full * `S` - Short
     */
    'variant_length'?: CourseRunWithCourseV3VariantLengthEnum;
    /**
     * Return the display label for the variant length.
     */
    'variant_length_label': string;
    'course_id': number;
    'upgrade_product_id': number | null;
    'upgrade_product_price': string | null;
    'upgrade_product_is_active': boolean | null;
    'course': CourseV3;
}

export const CourseRunWithCourseV3LanguageEnum = {
    AfZa: 'af_ZA',
    Ar: 'ar',
    Az: 'az',
    Bo: 'bo',
    Da: 'da',
    De: 'de',
    DeDe: 'de_DE',
    El: 'el',
    Es419: 'es_419',
    EsEs: 'es_ES',
    En: 'en',
    Fa: 'fa',
    Fr: 'fr',
    FrCa: 'fr_CA',
    He: 'he',
    Hi: 'hi',
    Hu: 'hu',
    Id: 'id',
    ItIt: 'it_IT',
    Ja: 'ja',
    Ka: 'ka',
    Kk: 'kk',
    Ko: 'ko',
    Lv: 'lv',
    Nl: 'nl',
    Pl: 'pl',
    PtBr: 'pt_BR',
    PtPt: 'pt_PT',
    Ro: 'ro',
    Ru: 'ru',
    Sq: 'sq',
    Sv: 'sv',
    Sw: 'sw',
    Te: 'te',
    Th: 'th',
    TrTr: 'tr_TR',
    Uk: 'uk',
    Uz: 'uz',
    Vi: 'vi',
    ZhCn: 'zh_CN',
    ZhHans: 'zh_HANS',
    ZhHk: 'zh_HK',
    Empty: '',
} as const;

export type CourseRunWithCourseV3LanguageEnum = typeof CourseRunWithCourseV3LanguageEnum[keyof typeof CourseRunWithCourseV3LanguageEnum];
export const CourseRunWithCourseV3VariantIndustryEnum = {
    E: 'E',
    F: 'F',
    Hc: 'HC',
    M: 'M',
    Empty: '',
} as const;

export type CourseRunWithCourseV3VariantIndustryEnum = typeof CourseRunWithCourseV3VariantIndustryEnum[keyof typeof CourseRunWithCourseV3VariantIndustryEnum];
export const CourseRunWithCourseV3VariantLengthEnum = {
    /**
    * * &#x60;&#x60; - Full
* &#x60;S&#x60; - Short
    */
    S: 'S',
    /**
    * 
    */
    Empty: '',
} as const;

export type CourseRunWithCourseV3VariantLengthEnum = typeof CourseRunWithCourseV3VariantLengthEnum[keyof typeof CourseRunWithCourseV3VariantLengthEnum];

/**
 * CourseRun serializer
 */
export interface CourseRunWithCourseV3Request {
    /**
     * The title of the course. This value is synced automatically with edX studio.
     */
    'title': string;
    /**
     * The day the course begins. This value is synced automatically with edX studio.
     */
    'start_date'?: string | null;
    /**
     * The last day the course is active. This value is synced automatically with edX studio.
     */
    'end_date'?: string | null;
    /**
     * The first day students can enroll. This value is synced automatically with edX studio.
     */
    'enrollment_start'?: string | null;
    /**
     * The last day students can enroll. This value is synced automatically with edX studio.
     */
    'enrollment_end'?: string | null;
    /**
     * The date beyond which the learner should not see link to this course run on their dashboard.
     */
    'expiration_date'?: string | null;
    'courseware_id': string;
    /**
     * The day certificates should be available to users. This value is synced automatically with edX studio.
     */
    'certificate_available_date'?: string | null;
    /**
     * The date beyond which the learner can not enroll in paid course mode.
     */
    'upgrade_deadline'?: string | null;
    'is_self_paced'?: boolean;
    /**
     * A string that identifies the set of runs that this run belongs to (example: \'R2\')
     */
    'run_tag': string;
    'live'?: boolean;
    /**
     * ISO 639-1 language code for this run (e.g. \'en\', \'zh\', \'fr\'). Leave blank for unspecified.  * `af_ZA` - af_ZA * `ar` - ar * `az` - az * `bo` - bo * `da` - da * `de` - de * `de_DE` - de_DE * `el` - el * `es_419` - es_419 * `es_ES` - es_ES * `en` - en * `fa` - fa * `fr` - fr * `fr_CA` - fr_CA * `he` - he * `hi` - hi * `hu` - hu * `id` - id * `it_IT` - it_IT * `ja` - ja * `ka` - ka * `kk` - kk * `ko` - ko * `lv` - lv * `nl` - nl * `pl` - pl * `pt_BR` - pt_BR * `pt_PT` - pt_PT * `ro` - ro * `ru` - ru * `sq` - sq * `sv` - sv * `sw` - sw * `te` - te * `th` - th * `tr_TR` - tr_TR * `uk` - uk * `uz` - uz * `vi` - vi * `zh_CN` - zh_CN * `zh_HANS` - zh_HANS * `zh_HK` - zh_HK
     */
    'language'?: CourseRunWithCourseV3RequestLanguageEnum;
    /**
     * Designates this run as the primary-language version for its run-tag group. The primary run is used as the canonical run when grouping language variants. If no run in a group is marked primary, the oldest run by creation date is treated as primary.
     */
    'is_primary_language'?: boolean;
    /**
     * Variant: Describes the industry the run is adapted for.  * `` - Original * `E` - Energy * `F` - Finance * `HC` - Healthcare * `M` - Manufacturing
     */
    'variant_industry'?: CourseRunWithCourseV3RequestVariantIndustryEnum;
    /**
     * Variant: Describes the length of the run (short/long).  * `` - Full * `S` - Short
     */
    'variant_length'?: CourseRunWithCourseV3RequestVariantLengthEnum;
}

export const CourseRunWithCourseV3RequestLanguageEnum = {
    AfZa: 'af_ZA',
    Ar: 'ar',
    Az: 'az',
    Bo: 'bo',
    Da: 'da',
    De: 'de',
    DeDe: 'de_DE',
    El: 'el',
    Es419: 'es_419',
    EsEs: 'es_ES',
    En: 'en',
    Fa: 'fa',
    Fr: 'fr',
    FrCa: 'fr_CA',
    He: 'he',
    Hi: 'hi',
    Hu: 'hu',
    Id: 'id',
    ItIt: 'it_IT',
    Ja: 'ja',
    Ka: 'ka',
    Kk: 'kk',
    Ko: 'ko',
    Lv: 'lv',
    Nl: 'nl',
    Pl: 'pl',
    PtBr: 'pt_BR',
    PtPt: 'pt_PT',
    Ro: 'ro',
    Ru: 'ru',
    Sq: 'sq',
    Sv: 'sv',
    Sw: 'sw',
    Te: 'te',
    Th: 'th',
    TrTr: 'tr_TR',
    Uk: 'uk',
    Uz: 'uz',
    Vi: 'vi',
    ZhCn: 'zh_CN',
    ZhHans: 'zh_HANS',
    ZhHk: 'zh_HK',
    Empty: '',
} as const;

export type CourseRunWithCourseV3RequestLanguageEnum = typeof CourseRunWithCourseV3RequestLanguageEnum[keyof typeof CourseRunWithCourseV3RequestLanguageEnum];
export const CourseRunWithCourseV3RequestVariantIndustryEnum = {
    E: 'E',
    F: 'F',
    Hc: 'HC',
    M: 'M',
    Empty: '',
} as const;

export type CourseRunWithCourseV3RequestVariantIndustryEnum = typeof CourseRunWithCourseV3RequestVariantIndustryEnum[keyof typeof CourseRunWithCourseV3RequestVariantIndustryEnum];
export const CourseRunWithCourseV3RequestVariantLengthEnum = {
    /**
    * * &#x60;&#x60; - Full
* &#x60;S&#x60; - Short
    */
    S: 'S',
    /**
    * 
    */
    Empty: '',
} as const;

export type CourseRunWithCourseV3RequestVariantLengthEnum = typeof CourseRunWithCourseV3RequestVariantLengthEnum[keyof typeof CourseRunWithCourseV3RequestVariantLengthEnum];

/**
 * Course serializer
 */
export interface CourseV3 {
    'id': number;
    'title': string;
    'readable_id': string;
    /**
     * Returns the type of object this is serializing.
     */
    'type': string;
    /**
     * Return true if the course should be included in the Learn catalog.  This is controlled in the CoursePage for the course, and will default to False if there isn\'t one.
     */
    'include_in_learn_catalog': boolean;
}
/**
 * Course serializer
 */
export interface CourseV3Request {
    'title': string;
    'readable_id': string;
}
export interface CourseVariantRunBadRequest {
    'detail': string;
}
/**
 * Serializer for the course variant run API.
 */
export interface CourseVariantRunsResponse {
    'id': number;
    'courseruns': Array<BaseCourseRun>;
}
/**
 * * `course` - course
 */

export const DisplayModeEnum = {
    /**
    * course
    */
    Course: 'course',
} as const;

export type DisplayModeEnum = typeof DisplayModeEnum[keyof typeof DisplayModeEnum];


/**
 * Whether a user may enroll, and a support-facing code when they may not.
 */
export interface EnrollmentEligibility {
    'enrollable': boolean;
    /**
     * Null when enrollable. CS_700 when an export compliance check rejected the learner; CS_701 when their profile is missing the information needed to run that check.
     */
    'reason_code': string | null;
}
export interface EnrollmentEligibilityNotFound {
    'detail': string;
}
export interface EnrollmentEligibilityThrottled {
    'detail': string;
}
/**
 * * `audit` - audit * `verified` - verified
 */

export const EnrollmentModeEnum = {
    /**
    * audit
    */
    Audit: 'audit',
    /**
    * verified
    */
    Verified: 'verified',
} as const;

export type EnrollmentModeEnum = typeof EnrollmentModeEnum[keyof typeof EnrollmentModeEnum];


/**
 * * `af_ZA` - af_ZA * `ar` - ar * `az` - az * `bo` - bo * `da` - da * `de` - de * `de_DE` - de_DE * `el` - el * `es_419` - es_419 * `es_ES` - es_ES * `en` - en * `fa` - fa * `fr` - fr * `fr_CA` - fr_CA * `he` - he * `hi` - hi * `hu` - hu * `id` - id * `it_IT` - it_IT * `ja` - ja * `ka` - ka * `kk` - kk * `ko` - ko * `lv` - lv * `nl` - nl * `pl` - pl * `pt_BR` - pt_BR * `pt_PT` - pt_PT * `ro` - ro * `ru` - ru * `sq` - sq * `sv` - sv * `sw` - sw * `te` - te * `th` - th * `tr_TR` - tr_TR * `uk` - uk * `uz` - uz * `vi` - vi * `zh_CN` - zh_CN * `zh_HANS` - zh_HANS * `zh_HK` - zh_HK
 */

export const LanguageEnum = {
    /**
    * af_ZA
    */
    AfZa: 'af_ZA',
    /**
    * ar
    */
    Ar: 'ar',
    /**
    * az
    */
    Az: 'az',
    /**
    * bo
    */
    Bo: 'bo',
    /**
    * da
    */
    Da: 'da',
    /**
    * de
    */
    De: 'de',
    /**
    * de_DE
    */
    DeDe: 'de_DE',
    /**
    * el
    */
    El: 'el',
    /**
    * es_419
    */
    Es419: 'es_419',
    /**
    * es_ES
    */
    EsEs: 'es_ES',
    /**
    * en
    */
    En: 'en',
    /**
    * fa
    */
    Fa: 'fa',
    /**
    * fr
    */
    Fr: 'fr',
    /**
    * fr_CA
    */
    FrCa: 'fr_CA',
    /**
    * he
    */
    He: 'he',
    /**
    * hi
    */
    Hi: 'hi',
    /**
    * hu
    */
    Hu: 'hu',
    /**
    * id
    */
    Id: 'id',
    /**
    * it_IT
    */
    ItIt: 'it_IT',
    /**
    * ja
    */
    Ja: 'ja',
    /**
    * ka
    */
    Ka: 'ka',
    /**
    * kk
    */
    Kk: 'kk',
    /**
    * ko
    */
    Ko: 'ko',
    /**
    * lv
    */
    Lv: 'lv',
    /**
    * nl
    */
    Nl: 'nl',
    /**
    * pl
    */
    Pl: 'pl',
    /**
    * pt_BR
    */
    PtBr: 'pt_BR',
    /**
    * pt_PT
    */
    PtPt: 'pt_PT',
    /**
    * ro
    */
    Ro: 'ro',
    /**
    * ru
    */
    Ru: 'ru',
    /**
    * sq
    */
    Sq: 'sq',
    /**
    * sv
    */
    Sv: 'sv',
    /**
    * sw
    */
    Sw: 'sw',
    /**
    * te
    */
    Te: 'te',
    /**
    * th
    */
    Th: 'th',
    /**
    * tr_TR
    */
    TrTr: 'tr_TR',
    /**
    * uk
    */
    Uk: 'uk',
    /**
    * uz
    */
    Uz: 'uz',
    /**
    * vi
    */
    Vi: 'vi',
    /**
    * zh_CN
    */
    ZhCn: 'zh_CN',
    /**
    * zh_HANS
    */
    ZhHans: 'zh_HANS',
    /**
    * zh_HK
    */
    ZhHk: 'zh_HK',
} as const;

export type LanguageEnum = typeof LanguageEnum[keyof typeof LanguageEnum];



export const NullEnum = {
} as const;

export type NullEnum = typeof NullEnum[keyof typeof NullEnum];


/**
 * CourseRunCertificate model serializer
 */
export interface V3CourseRunCertificate {
    'uuid': string;
    /**
     * Get the link at which this certificate will be served Format: /certificate/<uuid>/ Example: /certificate/93ebd74e-5f88-4b47-bb09-30a6d575328f/
     */
    'link': string;
}
/**
 * ProgramCertificate model serializer
 */
export interface V3ProgramCertificate {
    'uuid': string;
    /**
     * Get the link at which this certificate will be served Format: /certificate/program/<uuid>/ Example: /certificate/program/93ebd74e-5f88-4b47-bb09-30a6d575328f/
     */
    'link': string;
}
/**
 * Serializer for creating a program enrollment. Accepts a program_id and validates it corresponds to a live program.
 */
export interface V3ProgramEnrollmentRequestRequest {
    'program_id': number;
}
/**
 * Program Model Serializer v2
 */
export interface V3SimpleProgram {
    'title': string;
    'readable_id': string;
    'id': number;
    'program_type'?: string | null;
    'live'?: boolean;
    /**
     * Set to \'course\' to treat this program as a course in APIs.  * `course` - course
     */
    'display_mode'?: V3SimpleProgramDisplayModeEnum | null;
}

export const V3SimpleProgramDisplayModeEnum = {
    /**
    * * &#x60;course&#x60; - course
    */
    Course: 'course',
    /**
    * 
    */
    Empty: '',
} as const;

export type V3SimpleProgramDisplayModeEnum = typeof V3SimpleProgramDisplayModeEnum[keyof typeof V3SimpleProgramDisplayModeEnum];

/**
 * Serializer for user program enrollments.
 */
export interface V3UserProgramEnrollment {
    'program': V3SimpleProgram;
    'certificate': V3ProgramCertificate | null;
    'enrollment_mode'?: string;
}
/**
 * * `` - Original * `E` - Energy * `F` - Finance * `HC` - Healthcare * `M` - Manufacturing
 */

export const VariantIndustryEnum = {
    /**
    * Energy
    */
    E: 'E',
    /**
    * Finance
    */
    F: 'F',
    /**
    * Healthcare
    */
    Hc: 'HC',
    /**
    * Manufacturing
    */
    M: 'M',
} as const;

export type VariantIndustryEnum = typeof VariantIndustryEnum[keyof typeof VariantIndustryEnum];


/**
 * * `` - Full * `S` - Short
 */

export const VariantLengthEnum = {
    /**
    * Short
    */
    S: 'S',
} as const;

export type VariantLengthEnum = typeof VariantLengthEnum[keyof typeof VariantLengthEnum];



/**
 * CourseRunsApi - axios parameter creator
 */
export const CourseRunsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Report whether the authenticated user may enroll, without enrolling them. Only covers export compliance - it says nothing about whether the run or program is open for enrollment, live, or already enrolled in.  A POST because a cache miss triggers a live CyberSource export compliance check and records its result. Rate limited per user, so ask at the point of intent rather than pre-flighting a whole catalogue page.
         * @param {number} run_id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseRunsEnrollmentEligible: async (run_id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'run_id' is not null or undefined
            assertParamExists('courseRunsEnrollmentEligible', 'run_id', run_id)
            const localVarPath = `/api/v3/course_runs/{run_id}/enrollment-eligible/`
                .replace('{run_id}', encodeURIComponent(String(run_id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CourseRunsApi - functional programming interface
 */
export const CourseRunsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CourseRunsApiAxiosParamCreator(configuration)
    return {
        /**
         * Report whether the authenticated user may enroll, without enrolling them. Only covers export compliance - it says nothing about whether the run or program is open for enrollment, live, or already enrolled in.  A POST because a cache miss triggers a live CyberSource export compliance check and records its result. Rate limited per user, so ask at the point of intent rather than pre-flighting a whole catalogue page.
         * @param {number} run_id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async courseRunsEnrollmentEligible(run_id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EnrollmentEligibility>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.courseRunsEnrollmentEligible(run_id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CourseRunsApi.courseRunsEnrollmentEligible']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CourseRunsApi - factory interface
 */
export const CourseRunsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CourseRunsApiFp(configuration)
    return {
        /**
         * Report whether the authenticated user may enroll, without enrolling them. Only covers export compliance - it says nothing about whether the run or program is open for enrollment, live, or already enrolled in.  A POST because a cache miss triggers a live CyberSource export compliance check and records its result. Rate limited per user, so ask at the point of intent rather than pre-flighting a whole catalogue page.
         * @param {CourseRunsApiCourseRunsEnrollmentEligibleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseRunsEnrollmentEligible(requestParameters: CourseRunsApiCourseRunsEnrollmentEligibleRequest, options?: RawAxiosRequestConfig): AxiosPromise<EnrollmentEligibility> {
            return localVarFp.courseRunsEnrollmentEligible(requestParameters.run_id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for courseRunsEnrollmentEligible operation in CourseRunsApi.
 */
export interface CourseRunsApiCourseRunsEnrollmentEligibleRequest {
    readonly run_id: number
}

/**
 * CourseRunsApi - object-oriented interface
 */
export class CourseRunsApi extends BaseAPI {
    /**
     * Report whether the authenticated user may enroll, without enrolling them. Only covers export compliance - it says nothing about whether the run or program is open for enrollment, live, or already enrolled in.  A POST because a cache miss triggers a live CyberSource export compliance check and records its result. Rate limited per user, so ask at the point of intent rather than pre-flighting a whole catalogue page.
     * @param {CourseRunsApiCourseRunsEnrollmentEligibleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public courseRunsEnrollmentEligible(requestParameters: CourseRunsApiCourseRunsEnrollmentEligibleRequest, options?: RawAxiosRequestConfig) {
        return CourseRunsApiFp(this.configuration).courseRunsEnrollmentEligible(requestParameters.run_id, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CoursesApi - axios parameter creator
 */
export const CoursesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Fetch course outline data for the given course key from Open edX.
         * @param {string} course_id Open edX course key (URL-encoded recommended), e.g. course-v1%3AOpenedX%2BDemoX%2BDemoCourse
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseOutlineRetrieveV3: async (course_id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'course_id' is not null or undefined
            assertParamExists('courseOutlineRetrieveV3', 'course_id', course_id)
            const localVarPath = `/api/v3/courses/{course_id}/ol_openedx_outline/`
                .replace('{course_id}', encodeURIComponent(String(course_id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetch variant runs for a course(s) matching the specified filters.
         * @param {number} contract Contract to filter by
         * @param {Array<number>} course_id Course ID(s) to use
         * @param {string} [industry] Industry focus to retrieve
         * @param {string} [language] Language to retrieve
         * @param {string} [length] Language to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseVariantRunsV3: async (contract: number, course_id: Array<number>, industry?: string, language?: string, length?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contract' is not null or undefined
            assertParamExists('courseVariantRunsV3', 'contract', contract)
            // verify required parameter 'course_id' is not null or undefined
            assertParamExists('courseVariantRunsV3', 'course_id', course_id)
            const localVarPath = `/api/v3/courses/variant_runs/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (contract !== undefined) {
                localVarQueryParameter['contract'] = contract;
            }

            if (course_id) {
                localVarQueryParameter['course_id'] = course_id;
            }

            if (industry !== undefined) {
                localVarQueryParameter['industry'] = industry;
            }

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (length !== undefined) {
                localVarQueryParameter['length'] = length;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CoursesApi - functional programming interface
 */
export const CoursesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CoursesApiAxiosParamCreator(configuration)
    return {
        /**
         * Fetch course outline data for the given course key from Open edX.
         * @param {string} course_id Open edX course key (URL-encoded recommended), e.g. course-v1%3AOpenedX%2BDemoX%2BDemoCourse
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async courseOutlineRetrieveV3(course_id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CourseOutlineResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.courseOutlineRetrieveV3(course_id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.courseOutlineRetrieveV3']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fetch variant runs for a course(s) matching the specified filters.
         * @param {number} contract Contract to filter by
         * @param {Array<number>} course_id Course ID(s) to use
         * @param {string} [industry] Industry focus to retrieve
         * @param {string} [language] Language to retrieve
         * @param {string} [length] Language to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async courseVariantRunsV3(contract: number, course_id: Array<number>, industry?: string, language?: string, length?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CourseVariantRunsResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.courseVariantRunsV3(contract, course_id, industry, language, length, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.courseVariantRunsV3']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CoursesApi - factory interface
 */
export const CoursesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CoursesApiFp(configuration)
    return {
        /**
         * Fetch course outline data for the given course key from Open edX.
         * @param {CoursesApiCourseOutlineRetrieveV3Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseOutlineRetrieveV3(requestParameters: CoursesApiCourseOutlineRetrieveV3Request, options?: RawAxiosRequestConfig): AxiosPromise<CourseOutlineResponse> {
            return localVarFp.courseOutlineRetrieveV3(requestParameters.course_id, options).then((request) => request(axios, basePath));
        },
        /**
         * Fetch variant runs for a course(s) matching the specified filters.
         * @param {CoursesApiCourseVariantRunsV3Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseVariantRunsV3(requestParameters: CoursesApiCourseVariantRunsV3Request, options?: RawAxiosRequestConfig): AxiosPromise<Array<CourseVariantRunsResponse>> {
            return localVarFp.courseVariantRunsV3(requestParameters.contract, requestParameters.course_id, requestParameters.industry, requestParameters.language, requestParameters.length, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for courseOutlineRetrieveV3 operation in CoursesApi.
 */
export interface CoursesApiCourseOutlineRetrieveV3Request {
    /**
     * Open edX course key (URL-encoded recommended), e.g. course-v1%3AOpenedX%2BDemoX%2BDemoCourse
     */
    readonly course_id: string
}

/**
 * Request parameters for courseVariantRunsV3 operation in CoursesApi.
 */
export interface CoursesApiCourseVariantRunsV3Request {
    /**
     * Contract to filter by
     */
    readonly contract: number

    /**
     * Course ID(s) to use
     */
    readonly course_id: Array<number>

    /**
     * Industry focus to retrieve
     */
    readonly industry?: string

    /**
     * Language to retrieve
     */
    readonly language?: string

    /**
     * Language to retrieve
     */
    readonly length?: string
}

/**
 * CoursesApi - object-oriented interface
 */
export class CoursesApi extends BaseAPI {
    /**
     * Fetch course outline data for the given course key from Open edX.
     * @param {CoursesApiCourseOutlineRetrieveV3Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public courseOutlineRetrieveV3(requestParameters: CoursesApiCourseOutlineRetrieveV3Request, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).courseOutlineRetrieveV3(requestParameters.course_id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetch variant runs for a course(s) matching the specified filters.
     * @param {CoursesApiCourseVariantRunsV3Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public courseVariantRunsV3(requestParameters: CoursesApiCourseVariantRunsV3Request, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).courseVariantRunsV3(requestParameters.contract, requestParameters.course_id, requestParameters.industry, requestParameters.language, requestParameters.length, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * EnrollmentsApi - axios parameter creator
 */
export const EnrollmentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * API view set for user enrollments - v3
         * @param {number} id A unique integer value identifying this course run enrollment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        enrollmentsRetrieve: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('enrollmentsRetrieve', 'id', id)
            const localVarPath = `/api/v3/enrollments/{id}/`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new user enrollment - API v3
         * @param {CourseRunEnrollmentV3Request} [CourseRunEnrollmentV3Request] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userEnrollmentsCreateV3: async (CourseRunEnrollmentV3Request?: CourseRunEnrollmentV3Request, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/enrollments/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(CourseRunEnrollmentV3Request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Unenroll from a course - API v3
         * @param {number} id A unique integer value identifying this course run enrollment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userEnrollmentsDestroyV3: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('userEnrollmentsDestroyV3', 'id', id)
            const localVarPath = `/api/v3/enrollments/{id}/`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List user enrollments with B2B organization and contract information - API v3. Use ?exclude_b2b=true to filter out enrollments made through a B2B contract. Use ?org_id=<id> to filter enrollments by specific B2B organization.
         * @param {boolean} [exclude_b2b] Exclude B2B enrollments (enrollments made through a B2B contract)
         * @param {number} [org_id] Filter by B2B organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userEnrollmentsListV3: async (exclude_b2b?: boolean, org_id?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/enrollments/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (exclude_b2b !== undefined) {
                localVarQueryParameter['exclude_b2b'] = exclude_b2b;
            }

            if (org_id !== undefined) {
                localVarQueryParameter['org_id'] = org_id;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EnrollmentsApi - functional programming interface
 */
export const EnrollmentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EnrollmentsApiAxiosParamCreator(configuration)
    return {
        /**
         * API view set for user enrollments - v3
         * @param {number} id A unique integer value identifying this course run enrollment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async enrollmentsRetrieve(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CourseRunEnrollmentV3>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.enrollmentsRetrieve(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentsApi.enrollmentsRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new user enrollment - API v3
         * @param {CourseRunEnrollmentV3Request} [CourseRunEnrollmentV3Request] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userEnrollmentsCreateV3(CourseRunEnrollmentV3Request?: CourseRunEnrollmentV3Request, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CourseRunEnrollmentV3>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userEnrollmentsCreateV3(CourseRunEnrollmentV3Request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentsApi.userEnrollmentsCreateV3']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Unenroll from a course - API v3
         * @param {number} id A unique integer value identifying this course run enrollment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userEnrollmentsDestroyV3(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userEnrollmentsDestroyV3(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentsApi.userEnrollmentsDestroyV3']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List user enrollments with B2B organization and contract information - API v3. Use ?exclude_b2b=true to filter out enrollments made through a B2B contract. Use ?org_id=<id> to filter enrollments by specific B2B organization.
         * @param {boolean} [exclude_b2b] Exclude B2B enrollments (enrollments made through a B2B contract)
         * @param {number} [org_id] Filter by B2B organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userEnrollmentsListV3(exclude_b2b?: boolean, org_id?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CourseRunEnrollmentV3>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userEnrollmentsListV3(exclude_b2b, org_id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentsApi.userEnrollmentsListV3']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EnrollmentsApi - factory interface
 */
export const EnrollmentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EnrollmentsApiFp(configuration)
    return {
        /**
         * API view set for user enrollments - v3
         * @param {EnrollmentsApiEnrollmentsRetrieveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        enrollmentsRetrieve(requestParameters: EnrollmentsApiEnrollmentsRetrieveRequest, options?: RawAxiosRequestConfig): AxiosPromise<CourseRunEnrollmentV3> {
            return localVarFp.enrollmentsRetrieve(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new user enrollment - API v3
         * @param {EnrollmentsApiUserEnrollmentsCreateV3Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userEnrollmentsCreateV3(requestParameters: EnrollmentsApiUserEnrollmentsCreateV3Request = {}, options?: RawAxiosRequestConfig): AxiosPromise<CourseRunEnrollmentV3> {
            return localVarFp.userEnrollmentsCreateV3(requestParameters.CourseRunEnrollmentV3Request, options).then((request) => request(axios, basePath));
        },
        /**
         * Unenroll from a course - API v3
         * @param {EnrollmentsApiUserEnrollmentsDestroyV3Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userEnrollmentsDestroyV3(requestParameters: EnrollmentsApiUserEnrollmentsDestroyV3Request, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.userEnrollmentsDestroyV3(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * List user enrollments with B2B organization and contract information - API v3. Use ?exclude_b2b=true to filter out enrollments made through a B2B contract. Use ?org_id=<id> to filter enrollments by specific B2B organization.
         * @param {EnrollmentsApiUserEnrollmentsListV3Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userEnrollmentsListV3(requestParameters: EnrollmentsApiUserEnrollmentsListV3Request = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<CourseRunEnrollmentV3>> {
            return localVarFp.userEnrollmentsListV3(requestParameters.exclude_b2b, requestParameters.org_id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for enrollmentsRetrieve operation in EnrollmentsApi.
 */
export interface EnrollmentsApiEnrollmentsRetrieveRequest {
    /**
     * A unique integer value identifying this course run enrollment.
     */
    readonly id: number
}

/**
 * Request parameters for userEnrollmentsCreateV3 operation in EnrollmentsApi.
 */
export interface EnrollmentsApiUserEnrollmentsCreateV3Request {
    readonly CourseRunEnrollmentV3Request?: CourseRunEnrollmentV3Request
}

/**
 * Request parameters for userEnrollmentsDestroyV3 operation in EnrollmentsApi.
 */
export interface EnrollmentsApiUserEnrollmentsDestroyV3Request {
    /**
     * A unique integer value identifying this course run enrollment.
     */
    readonly id: number
}

/**
 * Request parameters for userEnrollmentsListV3 operation in EnrollmentsApi.
 */
export interface EnrollmentsApiUserEnrollmentsListV3Request {
    /**
     * Exclude B2B enrollments (enrollments made through a B2B contract)
     */
    readonly exclude_b2b?: boolean

    /**
     * Filter by B2B organization ID
     */
    readonly org_id?: number
}

/**
 * EnrollmentsApi - object-oriented interface
 */
export class EnrollmentsApi extends BaseAPI {
    /**
     * API view set for user enrollments - v3
     * @param {EnrollmentsApiEnrollmentsRetrieveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public enrollmentsRetrieve(requestParameters: EnrollmentsApiEnrollmentsRetrieveRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentsApiFp(this.configuration).enrollmentsRetrieve(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new user enrollment - API v3
     * @param {EnrollmentsApiUserEnrollmentsCreateV3Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public userEnrollmentsCreateV3(requestParameters: EnrollmentsApiUserEnrollmentsCreateV3Request = {}, options?: RawAxiosRequestConfig) {
        return EnrollmentsApiFp(this.configuration).userEnrollmentsCreateV3(requestParameters.CourseRunEnrollmentV3Request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Unenroll from a course - API v3
     * @param {EnrollmentsApiUserEnrollmentsDestroyV3Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public userEnrollmentsDestroyV3(requestParameters: EnrollmentsApiUserEnrollmentsDestroyV3Request, options?: RawAxiosRequestConfig) {
        return EnrollmentsApiFp(this.configuration).userEnrollmentsDestroyV3(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List user enrollments with B2B organization and contract information - API v3. Use ?exclude_b2b=true to filter out enrollments made through a B2B contract. Use ?org_id=<id> to filter enrollments by specific B2B organization.
     * @param {EnrollmentsApiUserEnrollmentsListV3Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public userEnrollmentsListV3(requestParameters: EnrollmentsApiUserEnrollmentsListV3Request = {}, options?: RawAxiosRequestConfig) {
        return EnrollmentsApiFp(this.configuration).userEnrollmentsListV3(requestParameters.exclude_b2b, requestParameters.org_id, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ProgramEnrollmentsApi - axios parameter creator
 */
export const ProgramEnrollmentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a program enrollment for the authenticated user.  Returns 200 if the user already has an active enrollment, 201 if a new enrollment was created or an inactive one was reactivated.
         * @param {V3ProgramEnrollmentRequestRequest} V3ProgramEnrollmentRequestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v3ProgramEnrollmentsCreate: async (V3ProgramEnrollmentRequestRequest: V3ProgramEnrollmentRequestRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'V3ProgramEnrollmentRequestRequest' is not null or undefined
            assertParamExists('v3ProgramEnrollmentsCreate', 'V3ProgramEnrollmentRequestRequest', V3ProgramEnrollmentRequestRequest)
            const localVarPath = `/api/v3/program_enrollments/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(V3ProgramEnrollmentRequestRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Unenroll the user from this program.  Returns 204 No Content. Idempotent - returns 204 even if not currently enrolled. Returns 404 if the program does not exist.
         * @param {number} program_id Program ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v3ProgramEnrollmentsDestroy: async (program_id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'program_id' is not null or undefined
            assertParamExists('v3ProgramEnrollmentsDestroy', 'program_id', program_id)
            const localVarPath = `/api/v3/program_enrollments/{program_id}/`
                .replace('{program_id}', encodeURIComponent(String(program_id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ViewSet for user program enrollments with v3 serializers.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v3ProgramEnrollmentsList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/program_enrollments/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ViewSet for user program enrollments with v3 serializers.
         * @param {number} program_id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v3ProgramEnrollmentsRetrieve: async (program_id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'program_id' is not null or undefined
            assertParamExists('v3ProgramEnrollmentsRetrieve', 'program_id', program_id)
            const localVarPath = `/api/v3/program_enrollments/{program_id}/`
                .replace('{program_id}', encodeURIComponent(String(program_id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProgramEnrollmentsApi - functional programming interface
 */
export const ProgramEnrollmentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProgramEnrollmentsApiAxiosParamCreator(configuration)
    return {
        /**
         * Create a program enrollment for the authenticated user.  Returns 200 if the user already has an active enrollment, 201 if a new enrollment was created or an inactive one was reactivated.
         * @param {V3ProgramEnrollmentRequestRequest} V3ProgramEnrollmentRequestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v3ProgramEnrollmentsCreate(V3ProgramEnrollmentRequestRequest: V3ProgramEnrollmentRequestRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v3ProgramEnrollmentsCreate(V3ProgramEnrollmentRequestRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProgramEnrollmentsApi.v3ProgramEnrollmentsCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Unenroll the user from this program.  Returns 204 No Content. Idempotent - returns 204 even if not currently enrolled. Returns 404 if the program does not exist.
         * @param {number} program_id Program ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v3ProgramEnrollmentsDestroy(program_id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v3ProgramEnrollmentsDestroy(program_id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProgramEnrollmentsApi.v3ProgramEnrollmentsDestroy']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * ViewSet for user program enrollments with v3 serializers.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v3ProgramEnrollmentsList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<V3UserProgramEnrollment>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v3ProgramEnrollmentsList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProgramEnrollmentsApi.v3ProgramEnrollmentsList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * ViewSet for user program enrollments with v3 serializers.
         * @param {number} program_id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v3ProgramEnrollmentsRetrieve(program_id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V3UserProgramEnrollment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v3ProgramEnrollmentsRetrieve(program_id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProgramEnrollmentsApi.v3ProgramEnrollmentsRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProgramEnrollmentsApi - factory interface
 */
export const ProgramEnrollmentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProgramEnrollmentsApiFp(configuration)
    return {
        /**
         * Create a program enrollment for the authenticated user.  Returns 200 if the user already has an active enrollment, 201 if a new enrollment was created or an inactive one was reactivated.
         * @param {ProgramEnrollmentsApiV3ProgramEnrollmentsCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v3ProgramEnrollmentsCreate(requestParameters: ProgramEnrollmentsApiV3ProgramEnrollmentsCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v3ProgramEnrollmentsCreate(requestParameters.V3ProgramEnrollmentRequestRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Unenroll the user from this program.  Returns 204 No Content. Idempotent - returns 204 even if not currently enrolled. Returns 404 if the program does not exist.
         * @param {ProgramEnrollmentsApiV3ProgramEnrollmentsDestroyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v3ProgramEnrollmentsDestroy(requestParameters: ProgramEnrollmentsApiV3ProgramEnrollmentsDestroyRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v3ProgramEnrollmentsDestroy(requestParameters.program_id, options).then((request) => request(axios, basePath));
        },
        /**
         * ViewSet for user program enrollments with v3 serializers.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v3ProgramEnrollmentsList(options?: RawAxiosRequestConfig): AxiosPromise<Array<V3UserProgramEnrollment>> {
            return localVarFp.v3ProgramEnrollmentsList(options).then((request) => request(axios, basePath));
        },
        /**
         * ViewSet for user program enrollments with v3 serializers.
         * @param {ProgramEnrollmentsApiV3ProgramEnrollmentsRetrieveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v3ProgramEnrollmentsRetrieve(requestParameters: ProgramEnrollmentsApiV3ProgramEnrollmentsRetrieveRequest, options?: RawAxiosRequestConfig): AxiosPromise<V3UserProgramEnrollment> {
            return localVarFp.v3ProgramEnrollmentsRetrieve(requestParameters.program_id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for v3ProgramEnrollmentsCreate operation in ProgramEnrollmentsApi.
 */
export interface ProgramEnrollmentsApiV3ProgramEnrollmentsCreateRequest {
    readonly V3ProgramEnrollmentRequestRequest: V3ProgramEnrollmentRequestRequest
}

/**
 * Request parameters for v3ProgramEnrollmentsDestroy operation in ProgramEnrollmentsApi.
 */
export interface ProgramEnrollmentsApiV3ProgramEnrollmentsDestroyRequest {
    /**
     * Program ID
     */
    readonly program_id: number
}

/**
 * Request parameters for v3ProgramEnrollmentsRetrieve operation in ProgramEnrollmentsApi.
 */
export interface ProgramEnrollmentsApiV3ProgramEnrollmentsRetrieveRequest {
    readonly program_id: number
}

/**
 * ProgramEnrollmentsApi - object-oriented interface
 */
export class ProgramEnrollmentsApi extends BaseAPI {
    /**
     * Create a program enrollment for the authenticated user.  Returns 200 if the user already has an active enrollment, 201 if a new enrollment was created or an inactive one was reactivated.
     * @param {ProgramEnrollmentsApiV3ProgramEnrollmentsCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public v3ProgramEnrollmentsCreate(requestParameters: ProgramEnrollmentsApiV3ProgramEnrollmentsCreateRequest, options?: RawAxiosRequestConfig) {
        return ProgramEnrollmentsApiFp(this.configuration).v3ProgramEnrollmentsCreate(requestParameters.V3ProgramEnrollmentRequestRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Unenroll the user from this program.  Returns 204 No Content. Idempotent - returns 204 even if not currently enrolled. Returns 404 if the program does not exist.
     * @param {ProgramEnrollmentsApiV3ProgramEnrollmentsDestroyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public v3ProgramEnrollmentsDestroy(requestParameters: ProgramEnrollmentsApiV3ProgramEnrollmentsDestroyRequest, options?: RawAxiosRequestConfig) {
        return ProgramEnrollmentsApiFp(this.configuration).v3ProgramEnrollmentsDestroy(requestParameters.program_id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ViewSet for user program enrollments with v3 serializers.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public v3ProgramEnrollmentsList(options?: RawAxiosRequestConfig) {
        return ProgramEnrollmentsApiFp(this.configuration).v3ProgramEnrollmentsList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ViewSet for user program enrollments with v3 serializers.
     * @param {ProgramEnrollmentsApiV3ProgramEnrollmentsRetrieveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public v3ProgramEnrollmentsRetrieve(requestParameters: ProgramEnrollmentsApiV3ProgramEnrollmentsRetrieveRequest, options?: RawAxiosRequestConfig) {
        return ProgramEnrollmentsApiFp(this.configuration).v3ProgramEnrollmentsRetrieve(requestParameters.program_id, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ProgramsApi - axios parameter creator
 */
export const ProgramsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Report whether the authenticated user may enroll, without enrolling them. Only covers export compliance - it says nothing about whether the run or program is open for enrollment, live, or already enrolled in.  A POST because a cache miss triggers a live CyberSource export compliance check and records its result. Rate limited per user, so ask at the point of intent rather than pre-flighting a whole catalogue page.
         * @param {number} program_id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        programsEnrollmentEligible: async (program_id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'program_id' is not null or undefined
            assertParamExists('programsEnrollmentEligible', 'program_id', program_id)
            const localVarPath = `/api/v3/programs/{program_id}/enrollment-eligible/`
                .replace('{program_id}', encodeURIComponent(String(program_id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProgramsApi - functional programming interface
 */
export const ProgramsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProgramsApiAxiosParamCreator(configuration)
    return {
        /**
         * Report whether the authenticated user may enroll, without enrolling them. Only covers export compliance - it says nothing about whether the run or program is open for enrollment, live, or already enrolled in.  A POST because a cache miss triggers a live CyberSource export compliance check and records its result. Rate limited per user, so ask at the point of intent rather than pre-flighting a whole catalogue page.
         * @param {number} program_id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async programsEnrollmentEligible(program_id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EnrollmentEligibility>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.programsEnrollmentEligible(program_id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProgramsApi.programsEnrollmentEligible']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProgramsApi - factory interface
 */
export const ProgramsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProgramsApiFp(configuration)
    return {
        /**
         * Report whether the authenticated user may enroll, without enrolling them. Only covers export compliance - it says nothing about whether the run or program is open for enrollment, live, or already enrolled in.  A POST because a cache miss triggers a live CyberSource export compliance check and records its result. Rate limited per user, so ask at the point of intent rather than pre-flighting a whole catalogue page.
         * @param {ProgramsApiProgramsEnrollmentEligibleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        programsEnrollmentEligible(requestParameters: ProgramsApiProgramsEnrollmentEligibleRequest, options?: RawAxiosRequestConfig): AxiosPromise<EnrollmentEligibility> {
            return localVarFp.programsEnrollmentEligible(requestParameters.program_id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for programsEnrollmentEligible operation in ProgramsApi.
 */
export interface ProgramsApiProgramsEnrollmentEligibleRequest {
    readonly program_id: number
}

/**
 * ProgramsApi - object-oriented interface
 */
export class ProgramsApi extends BaseAPI {
    /**
     * Report whether the authenticated user may enroll, without enrolling them. Only covers export compliance - it says nothing about whether the run or program is open for enrollment, live, or already enrolled in.  A POST because a cache miss triggers a live CyberSource export compliance check and records its result. Rate limited per user, so ask at the point of intent rather than pre-flighting a whole catalogue page.
     * @param {ProgramsApiProgramsEnrollmentEligibleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public programsEnrollmentEligible(requestParameters: ProgramsApiProgramsEnrollmentEligibleRequest, options?: RawAxiosRequestConfig) {
        return ProgramsApiFp(this.configuration).programsEnrollmentEligible(requestParameters.program_id, options).then((request) => request(this.axios, this.basePath));
    }
}



